In [1]:
# KUC

import pandas as pd
import numpy as np

In [2]:
v1 = pd.np.array([1, 2, 3])
v2 = pd.np.array([2, 3, 4])
print(v1.dot(v2))

20


/var/folders/jw/pk9yd5v978d_6j_wky4ptw480000gn/T/ipykernel_76655/2106926219.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  v1 = pd.np.array([1, 2, 3])
/var/folders/jw/pk9yd5v978d_6j_wky4ptw480000gn/T/ipykernel_76655/2106926219.py:2: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  v2 = pd.np.array([2, 3, 4])


In [3]:
np.matmul(v1,v2)

20

In [5]:
print(v1)
print(v2)
v3 = v1 * v2
print(v3)

[1 2 3]
[2 3 4]
[ 2  6 12]


In [6]:
(v1 * v2).sum()

20

In [7]:
# time?
import time
v1 = pd.np.arange(10000)
v2 = pd.np.arange(10000)
start= time.time()
v3=(v1 * v2).sum()
end=time.time()
print(v3)
print(end-start)



333283335000
0.0003371238708496094


/var/folders/jw/pk9yd5v978d_6j_wky4ptw480000gn/T/ipykernel_76655/3406650018.py:3: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  v1 = pd.np.arange(10000)
/var/folders/jw/pk9yd5v978d_6j_wky4ptw480000gn/T/ipykernel_76655/3406650018.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  v2 = pd.np.arange(10000)


In [8]:
start= time.time()
np.matmul(v1,v2)
end=time.time()
print(end-start)


7.772445678710938e-05
