In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.metrics import classification_report

In [2]:
test_data = pd.read_csv('../data/titanic/test.csv')
train_data = pd.read_csv('../data/titanic/train.csv')
gender_sub = pd.read_csv('../data/titanic/gender_submission.csv')

In [3]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
train_data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
train_data.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [6]:
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!


In [7]:
# get evaluation metrics of the model
print(classification_report(y, model.predict(X)))


              precision    recall  f1-score   support

           0       0.82      0.90      0.86       549
           1       0.80      0.69      0.74       342

    accuracy                           0.82       891
   macro avg       0.81      0.79      0.80       891
weighted avg       0.82      0.82      0.81       891



## DecisionTreeClassifier

In [94]:
train_data.columns 

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [95]:
X = train_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']].values

In [96]:
X[:5]

array([[3, 'male', 22.0, 1, 0, 7.25],
       [1, 'female', 38.0, 1, 0, 71.2833],
       [3, 'female', 26.0, 0, 0, 7.925],
       [1, 'female', 35.0, 1, 0, 53.1],
       [3, 'male', 35.0, 0, 0, 8.05]], dtype=object)

In [97]:
X_test = test_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']].values
X_test[:5]

array([[3, 'male', 34.5, 0, 0, 7.8292],
       [3, 'female', 47.0, 1, 0, 7.0],
       [2, 'male', 62.0, 0, 0, 9.6875],
       [3, 'male', 27.0, 0, 0, 8.6625],
       [3, 'female', 22.0, 1, 1, 12.2875]], dtype=object)

In [98]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['female','male'])
X[:,1] = le_sex.transform(X[:,1]) 

le_sex_test = preprocessing.LabelEncoder()
le_sex_test.fit(['female','male'])
X_test[:,1] = le_sex_test.transform(X_test[:,1]) 


In [99]:
y = train_data["Survived"]
y[0:5]

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [100]:
model = tree.DecisionTreeClassifier(criterion="entropy", max_depth = 4)
model.fit(X, y)


DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [101]:
predTree = model.predict(X_test)

In [102]:
print (predTree [0:10])

[0 0 0 0 0 0 0 0 0 0]


In [103]:
from sklearn import metrics
y_test = gender_sub["Survived"]
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_test, predTree))

DecisionTrees's Accuracy:  0.8157894736842105


In [104]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predTree})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!


## Try out other algorithm